blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from blog.views import ArticleListView, ArticleDetailView, ArticleAddView

app_name = 'blog'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('blog/article/add/', ArticleAddView.as_view(), name='article-add'),
    path('blog/article/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path('blog/article/create/', ArticleAddView.as_view(), name='article-create')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kodland/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.
from django.urls import reverse
from filer.utils.files import slugify


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="Статья", unique=True)
    slug = models.SlugField(max_length=200, verbose_name="Слаг", unique=True)
    content = RichTextField(config_name='default', verbose_name='Текст статьи', max_length=3000)
    pub_date = models.DateTimeField(verbose_name='Дата публикации', auto_now=True)
    image = models.ImageField(verbose_name='Изображение статьи', upload_to='uploads/%Y/%m/%d')

    def get_absolute_url(self):
        return reverse('blog:post', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from blog.models import Article


class AddArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', 'image']

blog/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, DetailView, CreateView

from blog.forms import AddArticleForm
from blog.models import Article


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/index.html'
    paginate_by = 10


class ArticleAddView(CreateView):
    model = Article
    template_name = 'blog/form_add_article.html'
    form_class = AddArticleForm
    success_url = reverse_lazy('blog:article-list')


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article.html'
    slug_url_kwarg = 'slug'

blog/templates/blog/article.html
{% extends 'blog/base.html' %}>
{% load static %}
{% load bootstrap4 %}
{% block banner %}{% endblock %}
{% block content %}
    <div class="container article w-50 mt-5 mb-5">
            <div class="row">
                <div class="col">
                    <h1>{{ object.title }}</h1>
                    <p>Опубликована: {{ object.pub_date }}</p>
                    <p class="text-center"><img src="{% get_media_prefix %}{{ object.image }}" alt="{{ object.title }}" class="img-fluid w-75"></p>
                    <p>{% autoescape off %}{{ object.content }}{% endautoescape %}</p>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet" media="screen">
    <title>Title</title>
</head>
<body>
<div class="container-fluid header">
    <div class="container">
        <div class="row">
            <div class="col-2"><img src="{% static 'images/logo.png' %}" alt="Логотип" class="header__logo"></div>
            <div class="col-2 align-self-center p-0"><a href="/" class="header__link nav-link mt-2">Блог</a></div>
            <div class="col-8 align-self-center text-right"><a href="{% url 'blog:article-add' %}" class="header__add-button btn">+ Добавить статью</a></div>
        </div>

</div>
</div>
{% block banner %}{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

blog/templates/blog/form_add_article.html
{% extends 'blog/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <div class="container article-add mt-5 pl-5 pr-5 pb-5">
        <h1>Добавить статью</h1>
        <div class="row">
            <div class="col">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-9">
                            {{ form.title }}
                        </div>
                        <div class="col">
                            <input type="submit" value="Опубликовать">
                        </div>
                    </div>
                    <div class="form-row mt-4">
                        <div class="col-9">
                            {{ form.content }}
                            {{ form.media }}
                        </div>
                        <div class="col">
                            <div class="article-add__load-image text-center">
                                <label for="image">Загрузить изображение</label>
                                {{ form.image }}
                                <span id='val'></span>
                                <button id='button' class="mt-1">Фаил</button>
                                <script>
                                    $(document).ready(function () {
                                        $('#button').click(function () {
                                            $("input[type='file']").trigger('click');
                                        })

                                        $("input[type='file']").change(function () {
                                            $('#val').text(this.value.replace(/C:\\fakepath\\/i, ''))
                                        })
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block banner %}
    {% if object_list %}
        <div class="container-fluid banner">
            <div class="container">
                <div class="row">

                    <div class="col-7">
                        <ul class="list-group list-group-flush mt-3 ml-2 banner__text-block">
                            <li class="list-group-item">NEW</li>
                            <li class="list-group-item">{{ object_list.first.title }}</li>
                            <li class="list-group-item">{% autoescape off %}
                                {{ object_list.first.content|truncatewords:35 }}{% endautoescape %}</li>
                            <li class="list-group-item"><a href="{% url 'blog:article-detail' object_list.first.slug %}"
                                                           class="btn banner__button">Читать</a></li>
                        </ul>

                    </div>
                    <div class="col-5 align-self-center"><img src="{% get_media_prefix %}{{ object_list.first.image }}"
                                                              alt="Баннер"
                                                              class="banner__image"></div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container mt-3 article-list ">
        <h1>Другие статьи</h1>
        <div class="row">
            {% for article in object_list|slice:'1:' %}
                <div class="col-4">
                    <a href="{% url 'blog:article-detail' article.slug %}">
                        <div class="card" style="width: 18rem;">
                            <p class="pt-3 pl-3 pr-3 text-dark small">{{ article.pub_date }}</p>
                            <img src="{% get_media_prefix %}{{ article.image }}" class="card-img-top img-preview"
                                 alt="{{ article.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ article.title }}</h5>

                            </div>

                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}